### ISSUE TITLE
"Unhandled Exception: System.SystemException: Invalid TOC entry" on some Redump verified images

### ISSUE THREAD

**Issue by oblivioncth** [zefie/zef-xiso-convert#1]
So far I've only tried converting all "A" games from the redump set, but already ran into this error with the following titles:

007 - Agent Under Fire (USA):  SHA256 - cf64e3dee720d4c958b61543022cbf0d0de4aa19af97158704a1fddaf5e7b9a6
Aggressive Inline (Europe) (En,Fr,De,Es): SHA256 - a5a263f874665414743b27def4e9bbd77a9468d97fe3a71b8b8827c671c8f90d
Aggressive Inline (USA): SHA256 - c81355d2c8d4eebe2eb52b4f6060571aaa028f73e0b4b5bdbab895b41e69aea7

No clue if its your code or XDVDMulleter.
```
zef-xiso-convert v1.0.6 by zefie ~ XISO functionality via XDVDMulleter libraries by Badsheepy
Converting XGD Format to XISO Format...

Unhandled Exception: System.SystemException: Invalid TOC entry
   at XBoxISO.XboxISOFileSource.ReadFileSystemData(Byte[] buffer, Int32 fsOffset, FileSystemEntry parentEntry, ISOFileStreamer ifs)
   at XBoxISO.XboxISOFileSource.ReadFileSystemData(Byte[] buffer, Int32 fsOffset, FileSystemEntry parentEntry, ISOFileStreamer ifs)
   at XBoxISO.XboxISOFileSource.ReadFileSystemData(Byte[] buffer, Int32 fsOffset, FileSystemEntry parentEntry, ISOFileStreamer ifs)
   at XBoxISO.XboxISOFileSource.ReadFileSystemData(Byte[] buffer, Int32 fsOffset, FileSystemEntry parentEntry, ISOFileStreamer ifs)
   at XBoxISO.XboxISOFileSource.ReadFileSystemData(Byte[] buffer, Int32 fsOffset, FileSystemEntry parentEntry, ISOFileStreamer ifs)
   at XBoxISO.XboxISOFileSource.ReadFileSystemData(Byte[] buffer, Int32 fsOffset, FileSystemEntry parentEntry, ISOFileStreamer ifs)
   at XBoxISO.XboxISOFileSource.ReadFileSystemData(Byte[] buffer, Int32 fsOffset, FileSystemEntry parentEntry, ISOFileStreamer ifs)
   at XBoxISO.XboxISOFileSource.ReadFileSystemData(Byte[] buffer, Int32 fsOffset, FileSystemEntry parentEntry, ISOFileStreamer ifs)
   at XBoxISO.XboxISOFileSource.ReadFileSystemData(Byte[] buffer, Int32 fsOffset, FileSystemEntry parentEntry, ISOFileStreamer ifs)
   at XBoxISO.XboxISOFileSource.ReadFileSystemData(Byte[] buffer, Int32 fsOffset, FileSystemEntry parentEntry, ISOFileStreamer ifs)
   at XBoxISO.XboxISOFileSource.ReadFileSystemData(Byte[] buffer, Int32 fsOffset, FileSystemEntry parentEntry, ISOFileStreamer ifs)
   at XBoxISO.XboxISOFileSource.ReadFileSystemData(Byte[] buffer, Int32 fsOffset, FileSystemEntry parentEntry, ISOFileStreamer ifs)
   at XBoxISO.XboxISOFileSource.ReadFileSystemData(Byte[] buffer, Int32 fsOffset, FileSystemEntry parentEntry, ISOFileStreamer ifs)
   at XBoxISO.XboxISOFileSource.ReadFileSystemData(Byte[] buffer, Int32 fsOffset, FileSystemEntry parentEntry, ISOFileStreamer ifs)
   at XBoxISO.XboxISOFileSource.ReadFileSystemData(Byte[] buffer, Int32 fsOffset, FileSystemEntry parentEntry, ISOFileStreamer ifs)
   at XBoxISO.XboxISOFileSource.ReadFileSystem()
   at XBoxISO.XboxISOFileSource.InitISO()
   at XBoxISO.XboxISOFileSource..ctor(String FileName)
   at ZefXISOConvert.Program.convertISO(String infile, String outfile)
   at ZefXISOConvert.Program.Main(String[] args)
```

**Comment by zefie** [comment]
I just confirmed this myself (with 007 - Agent Under Fire (USA)).

Not sure exactly what is causing it. I would assume XDVDMulleter due to the function that it is failing at, but I was also able to get a "System.IndexOutOfRangeException" error if I did not specify an output file, so something else is also going on.

I do not currently have my development environment available to me, but will check this again at the start of the new year.

**Comment by oblivioncth** [comment]
While there may be an issue on your end due to the oddity you noted, I do believe the core of the issue is from XDVDMulleter because I got another invalid TOC error when using the 10.2 beta GUI.

I'd report this to whoever maintains that as well but I can't find anything other than copies of its releases. No project pages or the like.

**Comment by johnjelinek** [comment]
Similar error for `Tony Hawk's Pro Skater 2x (USA)`

**Comment by johnjelinek** [comment]
Is XDVDMulleter open source? I can't find it anywhere to take a closer look.

**Comment by oblivioncth** [comment]
> Is XDVDMulleter open source? I can't find it anywhere to take a closer look.
I don't believe it is.

I ended up needing to convert a whole Redump set that had way too many failures with this tool to do by hand.

Using a build of Anarchy Linux with this procedure worked for all 2225 games I processed: 
https://www.reddit.com/r/originalxbox/comments/b740m3/comment/ewmkck6
